[project]
org-name= "kasthuriraajan"
version= "0.1.0"

[build-options]
observability-included=true

[dependencies]

[platform]
target = "java11"

    [[platform.libraries]]
    artafactId = "mysql-connector-java"
    version = "8.0.22"
    path = "./libs/mysql-connector-java-8.0.22.jar"
    groupId = "mysql"
    modules = ["dbconnector"]
